on:
 push:
   branches:
     - main
     - "feature/**"
   paths:
     - "src/**"
  
 pull-request:
   branches:
     - main
     - "feature/**"
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@4.2.2
    
    - name: run test
      run: npm test